language: python

python:
    - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

addons:
    apt:
        packages:
            - python-distutils-extra 
            - libimage-exiftool-perl
            - python-gobject
            - gir1.2-poppler-0.18
            - python-pdfrw 
            - python-gi-cairo
virtualenv:
    system_site_packages: true

install:
    - pushd ..
    - pip install --user --upgrade pip
    - pip install --user --upgrade setuptools
    - pip install --user coveralls
    - pip install --user codecov
    - pip install --user mutagen hachoir_core hachoir_parser
    - popd
    - python setup.py install

script:
    - coverage run --source=libmat --omit='*hachoir_editor*' setup.py test

after_success:
    - coveralls
    - codecov
