language: python

python:
    - "2.7"

virtualenv:
    system_site_packages: true

sudo: required

before_install:
    - sudo apt-get install python-distutils-extra libimage-exiftool-perl

install:
    - pushd ..
    - pip install --user --upgrade pip
    - pip install --user --upgrade setuptools
    - pip install --user coveralls
    - pip install --user codecov
    - popd
    - python setup.py install

script:
    - coverage run setup.py test

after_success:
    - coveralls
    - codecov
